version: '3'

services:

  python:
    build:
      context: ./python
    container_name: python
    volumes:
      - type: volume
        source: python
        target: /usr/src/app

  flask:
    build:
      context: ./flask
    container_name: flask
    volumes:
      - type: volume
        source: flask
        target: /usr/src/app

  db:
    build:
      context: ./db
    container_name: db
    command: mysqld --sql_mode=""
    ports:
      - "3308:3306"
    env_file:
      - ./db/db.env
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql

volumes:
  db:
  python: